// Copyright (C) 2026 William W. Davis, MSPM, PMP. All rights reserved.
// Licensed under the GNU General Public License v3.0.
// See LICENSE file in the project root for full license text.

// The pure half of export-chart.ts.
//
// WHY THIS FILE EXISTS
// `copyChartAsPng` cannot run under jsdom — html2canvas and Canvas2D `getImageData`
// have no implementation there — so the whole module sat at 0% coverage and was about
// to be written off as "browser-only, untestable". It is not: two genuinely pure
// decisions were buried inside the Canvas work, and colour handling is exactly the kind
// of logic whose edge cases nobody thinks about.
//
// Same move as B3 (`import-banner.ts`, `cdf-interpolate.ts`): logic wearing a framework
// coat, lifted out and tested directly. What remains in export-chart.ts is a thin shell
// that really is browser-only — the DOM walk, html2canvas, and the clipboard write.

/**
 * Computed values containing one of these CSS colour functions cannot be parsed by
 * html2canvas 1.4.1 and must be pre-resolved to rgb/rgba.
 *
 * Tailwind CSS v4 emits all three: `oklch(...)` is the default colour-token space,
 * `oklab(...)` appears directly in some properties, and `color-mix(in oklab, ...)` is
 * generated by opacity modifiers such as `bg-gray-50/50` — which is what broke the
 * scenario-comparison table copy.
 *
 * ⚠️ No `g` flag, deliberately. A global regex carries `lastIndex` across `.test()`
 * calls, so a shared module-level instance would return alternating true/false on
 * repeated identical input. This one is called once per CSS property on every element
 * in the tree.
 */
const UNSUPPORTED_COLOR_FN = /\b(?:oklch|oklab|color-mix)\(/;

/**
 * True when a computed CSS value contains a colour function html2canvas cannot parse.
 *
 * The trailing `\(` matters: it is the function CALL that fails to parse, so a value
 * merely mentioning the word (a custom property named `--oklch-brand`, say) is left
 * alone rather than pointlessly resolved.
 */
export function hasUnsupportedColorFunction(value: string): boolean {
  return UNSUPPORTED_COLOR_FN.test(value);
}

/**
 * Format one RGBA pixel — as read back from a 1×1 Canvas2D `getImageData` — into the
 * CSS colour string html2canvas will accept.
 *
 * Emits `rgb()` when fully opaque and `rgba()` otherwise, because an unnecessary alpha
 * channel changes how html2canvas composites the layer. Alpha is a 0–255 byte on the
 * way in and a 0–1 fraction on the way out, fixed to three decimals.
 */
export function formatPixelColor(r: number, g: number, b: number, a: number): string {
  return a < 255
    ? `rgba(${r},${g},${b},${(a / 255).toFixed(3)})`
    : `rgb(${r},${g},${b})`;
}
