// Copyright (C) 2026 William W. Davis, MSPM, PMP. All rights reserved.
// Licensed under the GNU General Public License v3.0.
// See LICENSE file in the project root for full license text.

import html2canvas from "html2canvas";
import {
  hasUnsupportedColorFunction,
  formatPixelColor,
} from "./export-chart-colors";

/**
 * Neutralize modern CSS color functions in the cloned DOM tree that
 * html2canvas 1.4.1 cannot parse. Tailwind CSS v4 uses several of these
 * by default:
 *  - `oklch(...)` — the default color space for color tokens.
 *  - `oklab(...)` — used directly in some properties.
 *  - `color-mix(in oklab, ...)` — generated by Tailwind opacity modifiers
 *    such as `bg-gray-50/50`. This is what broke the scenario-comparison
 *    table copy: alternating rows use `bg-gray-50/50`, which compiles to
 *    `color-mix(in oklab, var(--color-gray-50) 50%, transparent)`. Even
 *    after the `oklch` CSS variables are pre-resolved on :root, the
 *    `color-mix(in oklab, ...)` wrapper survives in computed values and
 *    triggers an "unsupported color function 'oklab'" parse error.
 *
 * Strategy: any computed value containing one of these function names is
 * routed through Canvas2D's `fillStyle` (which natively understands them
 * in modern browsers) to extract a plain rgb/rgba string that html2canvas
 * can render.
 *
 * Two-pass approach:
 *  1. Fix CSS custom properties on :root (Tailwind v4 stores colors there).
 *     This causes var() references everywhere to resolve to rgb automatically.
 *  2. Fix any remaining unsupported color functions in computed standard
 *     properties on all elements (both HTML and SVG — SVG elements inherit
 *     color from parent HTML).
 */
function neutralizeUnsupportedColors(doc: Document, clonedEl: HTMLElement): void {
  // Single reusable canvas to convert any modern color function → rgb/rgba
  const cvs = document.createElement("canvas");
  cvs.width = 1;
  cvs.height = 1;
  const ctx = cvs.getContext("2d")!;

  const resolve = (val: string): string => {
    ctx.clearRect(0, 0, 1, 1);
    ctx.fillStyle = "#000"; // fallback if next assignment fails silently
    ctx.fillStyle = val;
    ctx.fillRect(0, 0, 1, 1);
    const d = ctx.getImageData(0, 0, 1, 1).data;
    return formatPixelColor(d[0]!, d[1]!, d[2]!, d[3]!);
  };

  // Pass 1: Fix CSS custom properties (--color-*) on the cloned :root.
  const root = doc.documentElement;
  const rootStyles = getComputedStyle(root);
  for (let i = 0; i < rootStyles.length; i++) {
    const prop = rootStyles[i]!;
    if (prop.startsWith("--")) {
      const val = rootStyles.getPropertyValue(prop);
      if (hasUnsupportedColorFunction(val)) {
        root.style.setProperty(prop, resolve(val.trim()));
      }
    }
  }

  // Pass 2: Fix remaining unsupported color functions in standard properties.
  const fix = (el: HTMLElement | SVGElement) => {
    const s = getComputedStyle(el);
    for (let i = 0; i < s.length; i++) {
      const prop = s[i]!;
      if (prop.startsWith("--")) continue; // already handled on :root
      const val = s.getPropertyValue(prop);
      if (hasUnsupportedColorFunction(val)) {
        el.style.setProperty(prop, resolve(val));
      }
    }
  };
  fix(clonedEl);
  clonedEl.querySelectorAll("*").forEach((node) => {
    if (node instanceof HTMLElement || node instanceof SVGElement) fix(node);
  });
}

/** Options for {@link copyChartAsPng}. */
export interface CopyChartOptions {
  /**
   * Capture the element's whole scrollable width, not only the part scrolled into view.
   *
   * html2canvas renders what the element's own box shows. For an element that scrolls
   * sideways — the Gantt chart's container whenever Fit to window is off — that is the
   * scrolled-into-view part, and the PNG still looks complete, so nothing prompts anyone
   * to check it (WI-57). Opt-in: every other copy site captures an element that does not
   * scroll, and keeps exactly the capture it had.
   */
  captureFullWidth?: boolean;
  /**
   * Copy the element in its LIGHT theme, whatever the page's theme (WI-26).
   *
   * Called immediately before html2canvas, it switches the element to its light colours and
   * returns the function that switches it back. That function runs as soon as html2canvas
   * returns, before the copy is awaited. html2canvas copies the whole page synchronously inside
   * that call, and its copy of an SVG keeps the colours computed at that moment, so the copy is
   * light; the page is back in its own theme before the browser paints again, so the screen
   * never shows the light chart. The `dark` class is also taken off html2canvas's copy of the
   * document, for everything a stylesheet colours rather than the element itself.
   *
   * Opt-in, like `captureFullWidth`: every other copy site keeps exactly the capture it had.
   */
  captureLight?: () => () => void;
}

/**
 * Widen a sideways-scrolling element to its whole scroll width and stop it clipping, so
 * html2canvas renders all of it. An element with nothing hidden is left untouched.
 *
 * ⚠️ Call it on html2canvas's CLONE, in `onclone` — never on the live element, which
 * would change the page itself. Ending the scroll also discards the scroll position
 * html2canvas copies into its clone (`restoreNodeScroll`), so the capture starts at the
 * left edge even when the chart has been scrolled.
 *
 * `border-box` makes the arithmetic exact whatever the element's own box-sizing:
 * `offsetWidth` is the border-box width, and adding the hidden width to it gives the
 * width at which nothing is hidden. (Tailwind's preflight already makes every element
 * here border-box; this keeps the helper from depending on that.)
 */
export function expandToFullWidth(el: HTMLElement): void {
  const hidden = el.scrollWidth - el.clientWidth;
  if (hidden <= 0) return;
  el.style.boxSizing = "border-box";
  el.style.width = `${el.offsetWidth + hidden}px`;
  el.style.overflow = "visible";
}

/**
 * Give every element in the clone proportional numerals, so html2canvas draws digits at the
 * places it measured them (WI-62).
 *
 * html2canvas measures each run of text in its cloned DOM, where `tabular-nums` makes every
 * digit as wide as a 0, then draws the run on a 2D canvas, which has no numeric-spacing
 * setting and draws proportional digits. A narrow "1" therefore left a gap after its run: a
 * copied table showed "10 /05/2026", and right-aligned numbers stopped short of the edge.
 * Making the clone proportional too means what is measured is what is drawn.
 *
 * ⚠️ Call it on html2canvas's CLONE, in `onclone` — the page keeps its tabular digits. Only
 * elements whose numerals are not already `normal` are touched, and their children inherit it.
 */
export function setProportionalNumerals(el: HTMLElement): void {
  const fix = (node: HTMLElement | SVGElement) => {
    if (getComputedStyle(node).fontVariantNumeric !== "normal") {
      node.style.fontVariantNumeric = "normal";
    }
  };
  fix(el);
  el.querySelectorAll("*").forEach((node) => {
    if (node instanceof HTMLElement || node instanceof SVGElement) fix(node);
  });
}

/**
 * Start html2canvas on `element` and return its promise, NOT yet awaited.
 *
 * ⚠️ With `captureLight`, the restore runs in `finally`, before anything awaits the promise: the
 * light theme lasts exactly as long as the html2canvas call, which is when html2canvas takes its
 * copy of the page, and a throw from that call still puts the page back (WI-26).
 */
function startRender(
  element: HTMLElement,
  { captureFullWidth = false, captureLight }: CopyChartOptions,
): Promise<HTMLCanvasElement> {
  const options: Parameters<typeof html2canvas>[1] = {
    backgroundColor: "#ffffff",
    scale: 2, // Higher resolution
    ignoreElements: (el) => el.classList.contains("copy-image-button") || el.hasAttribute("data-capture-skip"),
    onclone: (doc, clonedEl) => {
      // First, so that nothing below computes or pins a colour under the dark theme (WI-26).
      if (captureLight) doc.documentElement.classList.remove("dark");
      if (captureFullWidth) expandToFullWidth(clonedEl);
      setProportionalNumerals(clonedEl);
      neutralizeUnsupportedColors(doc, clonedEl);
    },
  };
  const restore = captureLight ? enterLight(element, captureLight) : undefined;
  try {
    return html2canvas(element, options);
  } finally {
    restore?.();
  }
}

/** Switch `element` light through `captureLight`, and return the switch back (WI-26). */
function enterLight(element: HTMLElement, captureLight: () => () => void): () => void {
  const restore = captureLight();
  settleTransitions(element);
  return () => {
    restore();
    settleTransitions(element);
  };
}

/**
 * Finish, at their end values, the CSS transitions running inside `el` (WI-26).
 *
 * Switching the chart's colours starts a transition on every element that animates its colour
 * — the Gantt's dependency arrows do — and html2canvas copies such an element at the
 * transition's FIRST frame, in the old colour: measured in Chrome, a path with a 100 ms colour
 * transition was copied in its old colour, and the same path without one in its new. Finished, the new
 * colour lands at once, before the copy and again after the restore, so neither the copy nor the
 * screen shows a transition between the two themes. Only transitions: `finish()` throws on an
 * infinite animation. `getAnimations` brings style up to date before it answers; jsdom has no
 * Web Animations, so there this does nothing.
 */
function settleTransitions(el: HTMLElement): void {
  if (typeof el.getAnimations !== "function") return;
  for (const animation of el.getAnimations({ subtree: true })) {
    if (animation instanceof CSSTransition) animation.finish();
  }
}

/**
 * Copy a DOM element as a PNG image to the clipboard.
 * Two kinds of element are left out of the capture: those with the `copy-image-button` class,
 * and any element carrying the attribute `data-capture-skip` — a control that belongs on the
 * screen and not in the picture, such as the comparison table's Run row. html2canvas sizes the
 * canvas from its clone, which never holds a left-out element, so the picture closes up around it.
 * @param element The element to capture
 * @param options See {@link CopyChartOptions}
 */
export async function copyChartAsPng(
  element: HTMLElement,
  options: CopyChartOptions = {},
): Promise<void> {
  const canvas = await startRender(element, options);

  const blob = await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error("Failed to create PNG blob"))),
      "image/png"
    );
  });

  await navigator.clipboard.write([
    new ClipboardItem({ "image/png": blob }),
  ]);
}
